### ISSUE TITLE
Crul + BQWA issue

### ISSUE THREAD

**Issue by marcneander** [GuybrushGit/WarriorSim#61]
Hey,

First of, thanks for a great application.

I've been scratching my head with the result i'm getting and looking through the code I can't really find any obvious reasons as to why but running Crul + BQWA and then BQWA + Crul I see a difference in how many BT is used in the stats tab. But If I change "Prioritize BT/MS when AP is > than..." to an absurd number like 50000 I get the same number of BT in the stats tab.

This might not even be a bug and if It isn't why would Crul in MH be able to output more BT than BQWA in the same amount of time during execute phase?

Thanks,
Marc

**Comment by ups1dedomn** [comment]
How many simulations did you run with either setup? How long were the fights? What buffs and gear did you use?
If you have less than 2000 AP (default) you will never use BT during exe phase. If so, increasing the required AP to prioritize BT will still mean you never use BT during exe phase resulting in no difference.

Otherwise, faster attack speeds on main hand can correct for bad rotation management. Say the sim queues a new HS at 30 rage because BT is on 4.2s cd. Your MH swing timer started just before it queued it in this hypothetical scenario. With WCB Crul has 1.955 speed, BQWA has 2.21. Both MH and OH attack misses. BT now has 2.245s CD for Crul, or 1.99s CD for BQWA: only Crul will get one white hit swing before BT comes off CD.

Assuming high number of simulations were run and results were statistically significant, AP > 2000 and fight length > 1 min: Most likely you will see the same amount of BT use if you change the rage threshold for HS and WW. If those assumptions are correct and you still see this behavior, it might be a bug. If so, post screenshots of settings (including character stats on the left) and results.
